name: Super Linter

on:
  push:
  pull_request:

jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Super Linter
        uses: github/super-linter@v4

      - name: Run Super Linter
        run: |
          super-linter --fail-on-errors --github-token ${{ secrets.GITHUB_TOKEN }}
